title: Dmitry Murzinov
description: ASIC/FPGA Design Expert          
show_downloads: false
google_analytics: 
theme: jekyll-theme-minimal
#theme: jekyll-theme-tactile
highlighter: rouge

url: "http://cv.idoka.ru"
lsi: false

exclude: [LICENSE, CNAME, .gitignore. Gemfile, Gemfile.lock]

# build setting
permalink: pretty
